title = "よんログ"
author = "Seong Yong-ju"
DefaultContentLanguage = "ja"
disqusShortname = "blog-yong-ju-me"
enableInlineShortcodes = true
hasCJKLanguage = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
languageCode = "ja"
paginate = 5
pygmentsUseClasses = true
theme = "hugo-book"

# Book configuration
disablePathToLower = true
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 2

# Multi-lingual mode config
# There are different options to translate files
# See https://gohugo.io/content-management/multilingual/#translation-by-filename
# And https://gohugo.io/content-management/multilingual/#translation-by-content-directory
[languages.ja]
languageName = 'Japanese'
contentDir = 'content'
weight = 1

[params]
# Configure the date format used on the pages
# - In git information
# - In blog posts
BookDateFormat = "2006.01.02"
