name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.8

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - run: bun install
      - run: bun run build.server

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          aws s3 sync dist s3://yong-ju.blog
          aws cloudfront create-invalidation --distribution-id E1CW34R12A13S7 --paths '/*'
